### ISSUE TITLE
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by aftersss** [alibaba/fastjson#2736]
fastjson version: 1.2.60:
Run the following code:
```
        JSONObject s = JSONObject.parseObject("{1:2,3:4}");
        for(String s1 : s.keySet()){
            System.out.println(s1);
        }
```

It will throw exception like the following:
```
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at Test.main(Test.java:361)
```

JSONObject.keySet returns `Set<String>`, if I use fastjson version `1.2.29`, it works.

**Comment by Omega-Ariston** [comment]
Could you provide a simple demo that can reproduce the error? thanks :)

**Comment by aftersss** [comment]
Sorry, the demo is:
```
JSONObject s = JSONObject.parseObject("{1:2,3:4}");
        for(String s1 : s.keySet()){
            System.out.println(s1);
        }
```

**Comment by Omega-Ariston** [comment]
The reason is after this commit (https://github.com/alibaba/fastjson/commit/33eaec097f6cf7c23c7cf8dc08f9ca7b21f9f54c) from version 1.2.37, JSONObject is specially treated in `DefaultJSONParser.parseObject()` method. When a key-value pair is put into the inner map of JSONObject, the key type wasn't checked or converted. Should be a bug, I will create a PR later to fix this, thanks for noticing.

**Comment by kimmking** [comment]
And a tips: "{1:2,3:4}"  is not a standard json string
