### ISSUE TITLE
serialize for class org.springframework.data.domain.PageRequest is not correct

### ISSUE THREAD

**Issue by snakepoon** [alibaba/fastjson#2752]
version 1.2.60
When use JSON.toJSONString to convert object of class class org.springframework.data.domain.PageRequest to String, attribute sort is not correctly serialized as missing orders.
Please help to have a look. thx

**Comment by Omega-Ariston** [comment]
Could you provide a simple demo that can reproduce the situation?

**Comment by snakepoon** [comment]
> Could you provide a simple demo that can reproduce the situation?

I think the problem is in converting newer versoin of PageRequest, for the same object

when it parse spring-data-commons-1.13.7.RELEASE - org.springframework.data.domain.PageRequest:
{"offset":0,"pageNumber":0,"pageSize":10,"sort":[{"ascending":true,"descending":false,"direction":"ASC","ignoreCase":false,"nullHandling":"NATIVE","property":"id, desc"}]}Disconnected from the target VM, address: '127.0.0.1:63711', transport: 'socket'

while spring-data-commons-2.1.2.RELEASE:
{"offset":0,"pageNumber":0,"pageSize":10,"paged":true,"sort":{"empty":false,"sorted":true,"unsorted":false},"unpaged":false}

**Comment by Omega-Ariston** [comment]
The reason is,
The `Sort` class in spring-data-commons-1.13.7.RELEASE implemented `iterable` interface, hence fastjson used `MiscCodec` serializer to serialize this class, which used the `itertator` of this class to iterate certain attributes. In this case, `Order` was iterated.
While in 2.1.2.RELEASE, `Sort` class no longer implement `Iterable`, but implemented `Streamable` instead, which is a non-JDK class. Therefore, fastjson generated a  JavaBeanSerializer for this class by default, which is based on the getter and setter method defined in this class. However, there's no `getOrder()` method defined here, so the information was lost.
Solution: Use self-defined module to customize the serialization of `Sort` class.
Use case example: #2806 
因为spring-data-commons-1.13.7.RELEASE版本的Sort实现了Iterable接口,FastJson会使用MiscCodec序列化器输出，MiscCodec序列化器针对实现了Iterable接口的类会调用迭代方法，而Sort类中的迭代方法迭代的是Order。
而2.1.2版本的Sort实现接口改成了Streamable,该接口非JDK中的类，FastJson只能使用JavaBean序列化器来序列化，而JavaBean序列化器解析的是Sort，而Sort类中缺少getOrder方法，所以输出中没有order信息。

解决方案：可以采用自定义Module来改变对Sort的类的解析, 参照#2806

**Comment by snakepoon** [comment]
> The reason is,
> The `Sort` class in spring-data-commons-1.13.7.RELEASE implemented `iterable` interface, hence fastjson used `MiscCodec` serializer to serialize this class, which used the `itertator` of this class to iterate certain attributes. In this case, `Order` was iterated.
> While in 2.1.2.RELEASE, `Sort` class no longer implement `Iterable`, but implemented `Streamable` instead, which is a non-JDK class. Therefore, fastjson generated a JavaBeanSerializer for this class by default, which is based on the getter and setter method defined in this class. However, there's no `getOrder()` method defined here, so the information was lost.
> Solution: Use self-defined module to customize the serialization of `Sort` class.
> Use case example: #2806
> 因为spring-data-commons-1.13.7.RELEASE版本的Sort实现了Iterable接口,FastJson会使用MiscCodec序列化器输出，MiscCodec序列化器针对实现了Iterable接口的类会调用迭代方法，而Sort类中的迭代方法迭代的是Order。
> 而2.1.2版本的Sort实现接口改成了Streamable,该接口非JDK中的类，FastJson只能使用JavaBean序列化器来序列化，而JavaBean序列化器解析的是Sort，而Sort类中缺少getOrder方法，所以输出中没有order信息。
> 
> 解决方案：可以采用自定义Module来改变对Sort的类的解析, 参照#2806

Got it and thanks!!
