### ISSUE TITLE
"{\"v\":[\" \",\"abc\",\"x\",\"abc\"]}" with generic Map<String,char[]> still through parse?

### ISSUE THREAD

**Issue by ricardo0624** [alibaba/fastjson#776]
```java
String str1="{\"v\":[\" \",\"abc\",\"x\",\"abc\"]}";
Map<String, char[]> map = JSON.parseObject(str1,
new com.alibaba.fastjson.TypeReference<Map<String, char[]>>() {
});
System.out.println(new String(map.get("v")));
```
and then,it outpputs->  [" ","abc","x","abc"]
Is it right?
Actually If the generic is Map<String,String[]> or Map<String,char[][]>,it will correct.

**Comment by wenshao** [comment]
Get this result because:
```java
array.toString().toCharArray()
```

**Comment by ricardo0624** [comment]
I think may be the correct generic is Map&lt;String,String[]&gt; or Map&lt;String,char[][]&gt;,the generic Map&lt;String,char[]&gt; is confused.

**Comment by greenlaw110** [comment]
@wenshao 

Your response doesn't make sense. You put in something that is the direct cause of the unexpected behavior of FastJson, which needs to be fixed:

```java
array.toString().toCharArray();
```

The above implementation is crappy and doesn't capture the right intention.

While Jackson's behavior is really what's expected:

![image](https://cloud.githubusercontent.com/assets/216930/17652022/241b0f1a-62b6-11e6-81d6-e79b4d9d6d35.png)

This issue is **NOT** a question, it is a bug report about a misleading behavior of FastJson.

**Comment by greenlaw110** [comment]
@wenshao 

Thanks for taking this one as a bug, it makes me feel much more confortable with my decision of using FastJson as the built-in JSON library for [ActFramework](https://github.com/actframework/actframework)

**Comment by wenshao** [comment]
@greenlaw110 
Thank you choose fastjson. I will fix this problem in the next version.

**Comment by greenlaw110** [comment]
@wenshao 
Beautiful! Do you think there is any room for taking the issue #777 ?
